export interface Transaction {
    id: string,
    description: string,
    senderNodeId: string,
    receiverNodeId: string,
    senderNodeName: string,
    receiverNodeName: string,
    senderAmount: number,
    receiverAmount: number,
    senderCurrencyId: number,
    receiverCurrencyId: number,
    senderCurrencySymbol: string,
    receiverCurrencySymbol: string,
    date: Date,
    cancelled: boolean,
    userId: string,
    fromExternal?: boolean,
    toExternal?: boolean,
    order?: number
}
